/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
/**
 *
 * @author HP
 */

public class demo {
    public static void main(String[] args) {
        String dest = "test.pdf";

        try {
            // Initialize PDF writer
            PdfWriter writer = new PdfWriter(dest);

            // Initialize PDF document
            PdfDocument pdf = new PdfDocument(writer);

            // Initialize document
            Document document = new Document(pdf);

            // Add paragraph to the document
            document.add(new Paragraph("Hello, this is a test PDF generated by iText 7!"));

            // Close document
            document.close();

            System.out.println("PDF created successfully: " + dest);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
